### ISSUE TITLE
Request for ITALIAN

### ISSUE THREAD

**Issue by Michele-Minervini** [qiskit-community/qiskit-translations#1180]
### Summary

- I'd like to request the translation from ITALIAN
- I'd like to be a Translator

**Comment by SooluThomas** [comment]
Hi @Michele-Minervini, as mentioned [here](https://github.com/qiskit-community/qiskit-translations/blob/main/README.md#how-to-add-a-new-language-to-translate), we won't be adding any new languages to Crowdin untill further notice. This is due to a lot of upcoming changes in the documentation. But, in the meanwhile, feel free to use this issue to gather more volunteers for the translations.

**Comment by SooluThomas** [comment]
Thank you for your interest to contribute. As mentioned in [README](https://github.com/qiskit-community/qiskit-translations/blob/main/README.md), we are no longer supporting translations for the application docs.
